
spring:
  application:
    name: auth-server

#  config:
#    import: optional:configserver:http://localhost:8989

  datasource:
    url: jdbc:postgresql://localhost:5432/apna-cart?useSSL=false
    schema: public
    username: postgres
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create